import { Locale, Translation, SkillLevel } from './types';
import { 
  IconFootball, 
  IconTennis, 
  IconBasketball, 
  IconVolleyball, 
  IconBadminton, 
  IconBeachTennis,
  IconGenericSport 
} from './components/AppIcons';

export const TRANSLATIONS: Record<Locale, Translation> = {
  'pt-BR': {
    welcome: 'Bem-vindo ao Jogo',
    login: 'Entrar',
    register: 'Cadastrar',
    email: 'E-mail',
    password: 'Senha',
    home: 'Início',
    book: 'Reservar',
    events: 'Jogos',
    profile: 'Perfil',
    searchPlaceholder: 'Buscar quadras, esportes...',
    nearbyVenues: 'Locais Próximos',
    openGames: 'Jogos Abertos',
    myBookings: 'Minhas Reservas',
    myEvents: 'Meus Jogos',
    settings: 'Configurações',
    language: 'Idioma',
    logout: 'Sair',
    hostGame: 'Hospedar Jogo',
    join: 'Entrar',
    leave: 'Sair do Jogo',
    hostedBy: 'Organizado por',
    perHour: '/h',
    selectSport: 'Escolha o Esporte',
    selectVenue: 'Escolha o Local',
    selectDate: 'Escolha a Data',
    selectTime: 'Escolha o Horário',
    confirmBooking: 'Confirmar Reserva',
    success: 'Sucesso!',
    rating: 'Avaliação',
    skillLevel: 'Nível',
    beginner: 'Iniciante',
    intermediate: 'Intermediário',
    advanced: 'Avançado',
    pro: 'Profissional',
    loading: 'Carregando...',
    error: 'Ocorreu um erro',
    retry: 'Tentar novamente',
    noData: 'Nada encontrado',
    languageName: 'Português (Brasil)',
    distance: 'km',
    players: 'jogadores',
    cancel: 'Cancelar',
    submit: 'Enviar',
    discover: 'Descobrir',
    privacy: 'Privacidade',
    publicGame: 'Público',
    inviteOnly: 'Convidados',
    maxPlayers: 'Máx. Jogadores',
    description: 'Descrição',
    createGame: 'Criar Jogo',
    court: 'Quadra',
    slotsAvailable: 'vagas',
    total: 'Total',
    date: 'Data',
    time: 'Horário',
    venue: 'Local',
    sport: 'Esporte',
    joined: 'Confirmado',
    host: 'Anfitrião',
    yourRating: 'Sua Avaliação',
    ratePlayers: 'Avaliar Jogadores',
    role: 'Eu sou',
    player: 'Jogador',
    courtOwner: 'Dono de Quadra',
    dashboard: 'Painel',
    requests: 'Solicitações',
    calendar: 'Agenda',
    pendingRequests: 'Solicitações Pendentes',
    approve: 'Aprovar',
    decline: 'Recusar',
    chat: 'Chat do Grupo',
    typeMessage: 'Digite uma mensagem...',
    ownerDashboard: 'Painel do Proprietário',
    manageVenues: 'Gerenciar Locais',
    name: 'Nome Completo',
    phone: 'Telefone (WhatsApp)',
    confirmPassword: 'Confirmar Senha',
    alreadyHaveAccount: 'Já tem uma conta?',
    createAccount: 'Criar conta',
    passwordsDoNotMatch: 'As senhas não coincidem',
    verifyTitle: 'Verificar Conta',
    codeSentTo: 'Código enviado para',
    enterCode: 'Código de Verificação',
    verify: 'Verificar',
    resendCode: 'Reenviar Código',
    invalidCode: 'Código inválido (use 1234)',
    reviewBooking: 'Revisar Reserva',
    noSlotsAvailable: 'Sem horários disponíveis para hoje',
    duration: 'Duração',
    paymentMethod: 'Forma de Pagamento',
    pix: 'PIX (Instantâneo)',
    creditCard: 'Cartão de Crédito',
    payAtVenue: 'Pagar no Local',
    pay: 'Pagar',
    checkout: 'Checkout',
  },
  'en': {
    welcome: 'Welcome to Jogo',
    login: 'Login',
    register: 'Register',
    email: 'Email',
    password: 'Password',
    home: 'Home',
    book: 'Book',
    events: 'Games',
    profile: 'Profile',
    searchPlaceholder: 'Search venues, sports...',
    nearbyVenues: 'Nearby Venues',
    openGames: 'Open Games',
    myBookings: 'My Bookings',
    myEvents: 'My Games',
    settings: 'Settings',
    language: 'Language',
    logout: 'Logout',
    hostGame: 'Host Game',
    join: 'Join',
    leave: 'Leave Game',
    hostedBy: 'Hosted by',
    perHour: '/hr',
    selectSport: 'Select Sport',
    selectVenue: 'Select Venue',
    selectDate: 'Select Date',
    selectTime: 'Select Time',
    confirmBooking: 'Confirm Booking',
    success: 'Success!',
    rating: 'Rating',
    skillLevel: 'Level',
    beginner: 'Beginner',
    intermediate: 'Intermediate',
    advanced: 'Advanced',
    pro: 'Pro',
    loading: 'Loading...',
    error: 'An error occurred',
    retry: 'Retry',
    noData: 'Nothing found',
    languageName: 'English',
    distance: 'km',
    players: 'players',
    cancel: 'Cancel',
    submit: 'Submit',
    discover: 'Discover',
    privacy: 'Privacy',
    publicGame: 'Public',
    inviteOnly: 'Invite Only',
    maxPlayers: 'Max Players',
    description: 'Description',
    createGame: 'Host Game',
    court: 'Court',
    slotsAvailable: 'slots',
    total: 'Total',
    date: 'Date',
    time: 'Time',
    venue: 'Venue',
    sport: 'Sport',
    joined: 'Joined',
    host: 'Host',
    yourRating: 'Your Rating',
    ratePlayers: 'Rate Players',
    role: 'I am a',
    player: 'Player',
    courtOwner: 'Venue Owner',
    dashboard: 'Dashboard',
    requests: 'Requests',
    calendar: 'Calendar',
    pendingRequests: 'Pending Requests',
    approve: 'Approve',
    decline: 'Decline',
    chat: 'Group Chat',
    typeMessage: 'Type a message...',
    ownerDashboard: 'Owner Dashboard',
    manageVenues: 'Manage Venues',
    name: 'Full Name',
    phone: 'Phone (WhatsApp)',
    confirmPassword: 'Confirm Password',
    alreadyHaveAccount: 'Already have an account?',
    createAccount: 'Create account',
    passwordsDoNotMatch: 'Passwords do not match',
    verifyTitle: 'Verify Account',
    codeSentTo: 'Code sent to',
    enterCode: 'Verification Code',
    verify: 'Verify',
    resendCode: 'Resend Code',
    invalidCode: 'Invalid code (try 1234)',
    reviewBooking: 'Review Booking',
    noSlotsAvailable: 'No slots available for today',
    duration: 'Duration',
    paymentMethod: 'Payment Method',
    pix: 'PIX (Instant)',
    creditCard: 'Credit Card',
    payAtVenue: 'Pay at Venue',
    pay: 'Pay',
    checkout: 'Checkout',
  }
};

export const SPORTS = [
  { id: 'football', namePt: 'Futebol', nameEn: 'Football', icon: IconFootball },
  { id: 'tennis', namePt: 'Tênis', nameEn: 'Tennis', icon: IconTennis },
  { id: 'basketball', namePt: 'Basquete', nameEn: 'Basketball', icon: IconBasketball },
  { id: 'volleyball', namePt: 'Vôlei', nameEn: 'Volleyball', icon: IconVolleyball },
  { id: 'badminton', namePt: 'Badminton', nameEn: 'Badminton', icon: IconBadminton },
  { id: 'beach_tennis', namePt: 'Beach Tennis', nameEn: 'Beach Tennis', icon: IconBeachTennis },
  { id: 'beach_volleyball', namePt: 'Vôlei de Praia', nameEn: 'Beach Volleyball', icon: IconVolleyball },
];

export const SKILL_LABELS: Record<SkillLevel, { pt: string; en: string; color: string; border: string }> = {
  [SkillLevel.BEGINNER]: { pt: 'Iniciante', en: 'Beginner', color: 'bg-emerald-50 text-emerald-700', border: 'border-emerald-200' },
  [SkillLevel.INTERMEDIATE]: { pt: 'Intermediário', en: 'Intermediate', color: 'bg-blue-50 text-blue-700', border: 'border-blue-200' },
  [SkillLevel.ADVANCED]: { pt: 'Avançado', en: 'Advanced', color: 'bg-indigo-50 text-indigo-700', border: 'border-indigo-200' },
  [SkillLevel.PRO]: { pt: 'Profissional', en: 'Pro', color: 'bg-purple-50 text-purple-700', border: 'border-purple-200' },
};
